# Generated by Django 4.2.11 on 2024-12-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название пряника')),
                ('description', models.CharField(max_length=100, verbose_name='Состав пряника')),
                ('price', models.IntegerField(verbose_name='Цена пряника')),
            ],
            options={
                'verbose_name': 'Пряник',
                'verbose_name_plural': 'Пряники',
            },
        ),
    ]
