# Generated by Django 4.2.11 on 2024-12-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=50, verbose_name='ФИ клиента')),
                ('number', models.CharField(max_length=100, verbose_name='Цена пряиника')),
                ('order', models.IntegerField(verbose_name='Заказ клиента')),
                ('price', models.IntegerField(verbose_name='Итоговая сумма')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
