# Generated by Django 4.2.11 on 2024-12-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.TextField(max_length=9999, verbose_name='Заказ клиента'),
        ),
    ]
