# Generated by Django 4.2.11 on 2024-12-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_address_order_deadline_order_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.CharField(max_length=100, verbose_name='Итоговая сумма'),
        ),
    ]
