# Generated by Django 4.2.11 on 2024-12-25 08:14

from django.db import migrations
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_number_alter_order_price'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('objects', orders.models.OrderManager()),
            ],
        ),
    ]
