# Generated by Django 4.2.11 on 2024-12-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_data',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
