# Generated by Django 4.2.11 on 2024-12-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_order_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.JSONField(max_length=9999, verbose_name='Заказ клиента'),
        ),
    ]
