# Generated by Django 4.2.11 on 2024-12-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.TextField(max_length=9999, verbose_name='Заказ клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_data',
            field=models.CharField(max_length=5000, verbose_name='Данные заказа (JSON)'),
        ),
    ]
