# Generated by Django 4.2.11 on 2024-12-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_order_alter_order_order_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_data',
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(max_length=5000, verbose_name='Данные заказа (JSON)'),
        ),
    ]
