# Generated by Django 4.2.11 on 2024-12-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.CharField(max_length=9999, verbose_name='Заказ клиента'),
        ),
    ]
